# Site settings
title: Chad Spencer
email: chad@chadspencer.com
baseurl: ""
url: ""

# Exclude from processing.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - package.json
  - package-lock.json
  - webpack.mix.js

keep_files:
  - static
  - mix-manifest.json
